### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by dxa4481** [hrbrmstr/pewpew#13]
Hey, could you add a license file? I'd like to be able to use this code

**Comment by hrbrmstr** [comment]
The `index.html` already has `<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a>`. Do you really need a separate `LICENSE` file?

**Comment by dxa4481** [comment]
Nope, that'll do it. Sorry about that. I'll close this issue.
