### ISSUE TITLE
heroku deploy button

### ISSUE THREAD

**Issue by datapsi** [hrbrmstr/pewpew#17]
when i try to deploy this app on heroku with 'deploy on heroku' button i take this error on heroku:
 -----> Fetching set buildpack https://github.com/pearkes/heroku-buildpack-static... done
-----> Static app detected
-----> Bundling Apache v2.2.19
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 !     Push rejected, failed to compile Static app

**Comment by alexcpsec** [comment]
cc @blackfist 

Any thoughts?

**Comment by hrbrmstr** [comment]
The Apache build on Heroku seems to be busted (IMO). I can def blame Kevin
for that one :-)

**Comment by blackfist** [comment]
aww man, did I break production again? I'll take a look at this issue.

**Comment by vkremez** [comment]
datapsi-

Add index.php file with the following text in the root directory:
"<?php include_once("index.html"); ?>"

Then, it should work for you.

Vitali

**Comment by datapsi** [comment]
Yes i added index.php file and i changed app.json file and its work.

{
  "name": "IPew Attack Map",
  "description": "Now you can have your very own IP attack map",
  "keywords": [
    "security",
    "map",
    "pew"
  ],
  "repository": "https://github.com/datapsi/pewpew.git",
  "buildpacks": [
    {
      "url": "https://github.com/heroku/heroku-buildpack-php"
    }
  ]
}

**Comment by hrbrmstr** [comment]
If this is a universal fix (I didn't make and do not use the heroku
version) I can merge a PR for it.

**Comment by mexindian** [comment]
bump! This bug is still active, @datapsi did you ever propose your fix as a pull request?

**Comment by hrbrmstr** [comment]
Since @blackfist originated it and actually works at Heroku, I kinda expected a quick fix from him as well. Sadly, it seems too overwhelmingly difficult for him.

**Comment by datapsi** [comment]
Hi  @mexindian its working after changes** for me on heroku. You can use `Deploy to HEROKU` button from here https://github.com/datapsi/pewpew

**Yes i added index.php file and i changed app.json file and its work.

{
"name": "IPew Attack Map",
"description": "Now you can have your very own IP attack map",
"keywords": [
"security",
"map",
"pew"
],
"repository": "https://github.com/datapsi/pewpew.git",
"buildpacks": [
{
"url": "https://github.com/heroku/heroku-buildpack-php"
}
]
}_**

**Comment by hrbrmstr** [comment]
Definitely going to figure out some way to get the Heroku deploy working w/o forcing folks to run an insecure web configuration (php shldn't be necessary).

**Comment by hydrosquall** [comment]
Bumping this thread, as while @datapsi 's forked button deploys, the application won't work since all the resources are loaded over HTTP rather than HTTPS so the app fails to load :(

Excited to try it out though :)

**Comment by hydrosquall** [comment]
Separately- given that this is a frontend-only app so no server-side processing is necessary (aka it's a static site), there might be a way to let people deploy this conveniently using github-pages.
