### ISSUE TITLE
site Not working

### ISSUE THREAD

**Issue by aravindiiitb** [hrbrmstr/pewpew#23]
The URL is not working. Is the site down ?

**Comment by hrbrmstr** [comment]
it is, indeed, down (transitioning hosting companies and it doesn't get
enough hits to have warranted keeping it up during transition). I'll have
it back up later this week

**Comment by aravindiiitb** [comment]
Thanks for the information. 
Waiting for it to get back in shape asap.

**Comment by brudis-r7** [comment]
Shld be up now. I had to wait for a Hadoop job to finish so I did a quick clone/deploy to the new system.

**Comment by MaxiTOR994** [comment]
Looks like its down again

**Comment by hrbrmstr** [comment]
and tis up (the site it 100% un-monitored since it has no useful purpose so this was very helpful! #ty)

may take DNS a bit to make it to all the caches (tis on a new box)

**Comment by psharma04** [comment]
If you want, ill keep an eye on it in my spare time
