### ISSUE TITLE
Feature request: Destination Location

### ISSUE THREAD

**Issue by dtklein** [hrbrmstr/pewpew#8]
As a user of this tool, I would like to be able to specify my organization's location (by country code or LATLONG) as the destination of the attacks and be able to only visualize simulated attacks targetting my organization's location. This capability will enable me to use this tool in incident response drills and what-if scenarios, wherein we are simulating an attack in-progress.

**Comment by alexcpsec** [comment]
Sounds like a legit request. I for one would find it incredible if this was actually used for serious purposes. :)

**Comment by hrbrmstr** [comment]
Done. The latest code in `master` has this feature. Example - http://ocularwarfare.com/ipew/index.html?org_name=hrbrmstr&drill_mode=1&lat=43.2672&lon=-70.8617

**Comment by dtklein** [comment]
Awesome! Thank you so much. 


--
david t. klein
david@tenar.us

@dtklein
